config/routes.rb
Rails.application.routes.draw do

	devise_for :users, controllers: {
	  sessions:      'users/sessions',
	  passwords:     'users/passwords',
	  registrations: 'users/registrations'
	}
	devise_for :admins, controllers: {
	  sessions:      'admins/sessions'
	}

	# 管理者側
  namespace :admins do
    get 'top', to: 'users#top'
    resources :users, only: [:index, :show, :edit, :update]
  end

  # ECサイト
  root to: 'homes#home'
  get '/about', to: 'homes#about'
  get '/search', to: 'search#search'
  get '/messages/create', to: 'messages#create'
  get '/rooms/create', to: 'rooms#create'
  get '/rooms/show', to: 'rooms#show'

  resources :users, only: [:show, :edit, :update] do
    get '/follow', to: 'relationships#follow'
    get '/follower', to: 'relationships#follower'
    get '/password/edit', to:"users#password_edit"
    patch '/password/edit' ,to: "users#password_update"
    get '/status', to: 'users#status'
    patch '/status', to: 'users#status_update'
    resource :relationships, only: [:create, :destroy]
  end
  resources :inquiries, only: [:create]
  resources :messages, only: [:create] #DM機能
  resources :rooms, only: [:create,:show]

  resources :posts, only: [:index, :create, :show, :edit, :update, :destroy] do
    resource :likes, only: [:create, :destroy] #いいね
    resource :favorites, only: [:create, :destroy] #お気に入り
    resources :comments, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :post
	validates :comment, presence: true, length: { maximum: 100 }
end

app/models/entry.rb
class Entry < ApplicationRecord
	belongs_to :user
	belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/image.rb
class Image < ApplicationRecord
	attachment :image
	belongs_to :post, optional: true
	belongs_to :user, optional: true
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  	validates :email, presence: true, length: {maximum:255},
                    format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}
  	validates :message, presence: true
	validates :name, presence: true, length: { in: 2..20 }
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/message.rb
class Message < ApplicationRecord
	validates :message, presence: true, length: { maximum: 200 }
	belongs_to :user
	belongs_to :room
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :likes, dependent: :destroy
	has_many :favorites, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :post_images, class_name: "Image", dependent: :destroy
	accepts_attachments_for :post_images, attachment: :image

	validates :title, presence: true, length: { maximum: 20 }
	validates :article, presence: true, length: { maximum: 100 }

	acts_as_taggable

	def add_images(params)
		params.each do |image|
	   	 new_image = Image.new(image: image)
	   	 new_image.post_id = self.id
	   	 new_image.user_id = self.user_id
	   	 return false unless new_image.save!
		end
	end

    def liked_by?(user)
        likes.where(user_id: user.id).exists?
    end

    def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follow, class_name: "User"
	belongs_to :follower, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
	has_many :messages, dependent: :destroy
	has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

	has_many :posts, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :follow, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
	has_many :follows, through: :follow
	has_many :follower, foreign_key: "follow_id", class_name: "Relationship", dependent: :destroy
	has_many :followers, through: :follower
	has_many :images, dependent: :destroy
	has_many :likes, dependent: :destroy
	has_many :favorites, dependent: :destroy
	has_many :messages, dependent: :destroy
  	has_many :entries, dependent: :destroy

	attachment :profile_image
	validates :name, presence: true, length: { in: 2..20 }
	validates :name_kana, presence: true, format: {with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
	validates :nickname, presence: true, length: { maximum: 20 }
	validates :introduction, length: { maximum: 50 }
	validates :one_word, length: { maximum: 20 }

	def active_for_authentication?
		super && (self.come_out == false)
	end

	def following?(user)
		follow.find_by(follow_id: user)
	end
	def follow_user(user_id)
		follow.create(follow_id: user_id)
	end
	def unfollow(user_id)
		follow.find_by(follow_id: user_id).destroy
	end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	before_action :authenticate_user!
  def follow
  	@user = User.find(params[:user_id])
  	@follows = @user.follows
  end

  def follower
  	@user = User.find(params[:user_id])
    @followers = @user.followers
  end

  def create
  	current_user.follow_user(params[:user_id])
    redirect_back(fallback_location: root_url)
  end

  def destroy
  	current_user.unfollow(params[:user_id])
  	redirect_back(fallback_location: root_url)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/relationships/_relation.html.erb
<% if current_user.following?(user) %>
	<%= link_to ' 解除', user_relationships_path(user.id), method: :delete, class: 'fas fa-user-minus' %>
<% else %>
	<%= link_to ' フォロー', user_relationships_path(user.id), method: :POST, class: 'fas fa-user-plus' %>
<% end %>

app/views/relationships/follow.html.erb
<div class="row">
	<div class="col-xs-8 col-xs-offset-2">
		<h2 class="heading">フォロー</h2>
		<table class="table">
			<thead>
				<tr>
					<th></th>
					<th>ニックネーム</th>
					<th>ひとこと</th>
					<th></th>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<% @follows.each do |user| %>
				<tr>
					<td>
		                <%= link_to user_path(user.id) do %>
		                	<%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_user.jpg", size:'70x70', class: 'user-image' %>
		                <% end %>
					</td>
					<td><%= user.nickname %></td>
					<td><%= user.one_word %></td>
					<td>フォロー数: <%= user.follows.count %></td>
					<td>フォロワー数: <%= user.followers.count %></td>
					<td>
						<% if current_user != user %>
							<%= render 'relationships/relation', user:user %>
						<% end %>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/relationships/follower.html.erb
<div class="row">
	<div class="col-xs-8 col-xs-offset-2">
		<h2 class="heading">フォロワー</h2>
		<table class="table">
			<thead>
				<tr>
					<th></th>
					<th>ニックネーム</th>
					<th>ひとこと</th>
					<th></th>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<% @followers.each do |user| %>
				<tr>
					<td>
		                <%= link_to user_path(user.id) do %>
		                	<%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_user.jpg", size:'70x70', class: 'user-image' %>
		                <% end %>
					</td>
					<td><%= user.nickname %></td>
					<td><%= user.one_word %></td>
					<td>フォロー数: <%= user.follows.count %></td>
					<td>フォロワー数: <%= user.followers.count %></td>
					<td>
						<% if current_user != user %>
							<%= render 'relationships/relation', user:user %>
						<% end %>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>