config/routes.rb
Rails.application.routes.draw do

	devise_for :users, controllers: {
	  sessions:      'users/sessions',
	  passwords:     'users/passwords',
	  registrations: 'users/registrations'
	}
	devise_for :admins, controllers: {
	  sessions:      'admins/sessions'
	}

	# 管理者側
  namespace :admins do
    get 'top', to: 'users#top'
    resources :users, only: [:index, :show, :edit, :update]
  end

  # ECサイト
  root to: 'homes#home'
  get '/about', to: 'homes#about'
  get '/search', to: 'search#search'
  get '/messages/create', to: 'messages#create'
  get '/rooms/create', to: 'rooms#create'
  get '/rooms/show', to: 'rooms#show'

  resources :users, only: [:show, :edit, :update] do
    get '/follow', to: 'relationships#follow'
    get '/follower', to: 'relationships#follower'
    get '/password/edit', to:"users#password_edit"
    patch '/password/edit' ,to: "users#password_update"
    get '/status', to: 'users#status'
    patch '/status', to: 'users#status_update'
    resource :relationships, only: [:create, :destroy]
  end
  resources :inquiries, only: [:create]
  resources :messages, only: [:create] #DM機能
  resources :rooms, only: [:create,:show]

  resources :posts, only: [:index, :create, :show, :edit, :update, :destroy] do
    resource :likes, only: [:create, :destroy] #いいね
    resource :favorites, only: [:create, :destroy] #お気に入り
    resources :comments, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

	has_many :posts, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :follow, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
	has_many :follows, through: :follow
	has_many :follower, foreign_key: "follow_id", class_name: "Relationship", dependent: :destroy
	has_many :followers, through: :follower
	has_many :images, dependent: :destroy
	has_many :likes, dependent: :destroy
	has_many :favorites, dependent: :destroy
	has_many :messages, dependent: :destroy
  	has_many :entries, dependent: :destroy

	attachment :profile_image
	validates :name, presence: true, length: { in: 2..20 }
	validates :name_kana, presence: true, format: {with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
	validates :nickname, presence: true, length: { maximum: 20 }
	validates :introduction, length: { maximum: 50 }
	validates :one_word, length: { maximum: 20 }

	def active_for_authentication?
		super && (self.come_out == false)
	end

	def following?(user)
		follow.find_by(follow_id: user)
	end
	def follow_user(user_id)
		follow.create(follow_id: user_id)
	end
	def unfollow(user_id)
		follow.find_by(follow_id: user_id).destroy
	end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
	before_action :authenticate_admin!
  def top
  	@user_count = User.where("Date(created_at) = '#{Date.today}'").count
  end

  def index
    case params[:user_case]
    when "today"
      @users = User.where("Date(created_at) = '#{Date.today}'").page(params[:page])
    when "all"
      @users = User.page(params[:page])
    end
  end

  def show
  	@user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "変更しました"
      redirect_to admins_user_path(@user.id)
    else
      @user = User.find(params[:id])
      flash.now[:alert] = '変更に失敗しました'
      render :edit
    end
  end

  private
  def user_params
      params.require(:user).permit(:name, :name_kana, :nickname, :profile_image, :introduction ,:one_word, :email, :come_out)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
    before_action :reject_user, only: [:create]

  protected

  def reject_user
    @user = User.find_by(email: params[:user][:email].downcase)
    if @user
      if (@user.valid_password?(params[:user][:password]) && (@user.active_for_authentication? == false))
        flash[:alert] = "退会済みです。"
        redirect_to new_user_session_path
      end
    else
      flash[:alert] = "必須項目を入力してください。"
    end
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
  def show
  	@user = User.find(params[:id])
    @user_posts = @user.posts.page(params[:page]).reverse_order
    @slide = @user_posts.shuffle

    @current_user_entry = Entry.where(user_id: current_user.id)
    @user_entry = Entry.where(user_id: @user.id)
    if @user.id != current_user.id
      @current_user_entry.each do |current_user|
        @user_entry.each do |user|
          if current_user.room_id == user.room_id then
            @isRoom = true
            @roomId = current_user.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
      if @user.update(user_params)
        flash[:update] = "登録内容を変更しました"
        redirect_to user_path(@user.id)
      else
        @userfind = User.find(params[:id])
        flash.now[:alert] = '変更に失敗しました'
        render :edit
      end
  end

  def password_edit
    @user = current_user
  end

  def password_update
    @user = current_user
    if @user.update(password_params)
      flash[:notice] = 'パスワードを変更しました。'
      redirect_to root_path
    else
      @userfind = current_user
      flash.now[:alert] =  'パスワードが変更できませんでした。'
      render :password_edit
    end
  end

  def status
    @user = current_user
  end

  def status_update #退会アクション
    @user = current_user
    @user.update(come_out: true)
    reset_session
    flash[:alert] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
  end

  private
  def user_params
      params.require(:user).permit(:name, :name_kana, :nickname, :profile_image, :introduction ,:one_word, :email)
  end

  def password_params
      params.require(:user).permit(:password, :password_confirmation)
  end
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user-info.html.erb
<table class="table user-info">
	<thead>
		<tr>
			<th class="row">
				<div class="col-xs-5">
					<%= link_to user_path(user) do %>
						<%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_user.jpg", size:'70x70', class: 'user-image' %>
					<% end %>
				</div>
				<div class="col-xs-7 --right">
					<%= user.nickname %><br>
					<% if user.id == current_user.id %>
						<%= link_to '', edit_user_path(user), class: 'fas fa-user-edit' %>
					<% end %>
				</div>
			</th>
		</tr>
	</thead>
	<tbody>
		<% if user.id != current_user.id %>
			<tr>
				<td><%= render 'relationships/relation', user:user %></td>
			</tr>
		<% end %>
		<% if user.introduction.present? %>
			<tr>
				<td class="introduction"><%= user.introduction %></td>
			</tr>
		<% end %>
		<% if user.one_word.present? %>
			<tr>
				<td class="">ひとこと　<%= user.one_word %></td>
			</tr>
		<% end %>
		<tr>
			<td><%= link_to user_path(user) do %>
					投稿 <%= user.posts.count %> 件
				<% end %>
			</td>
		</tr>
		<tr>
			<td><%= link_to user_follow_path(user.id) do %>
					フォロー <%= user.follows.count %> 人
				<% end %>
			</td>
		</tr>
		<tr>
			<td><%= link_to user_follower_path(user.id) do %>
					フォロワー <%= user.followers.count %> 人
				<% end %>
			</td>
		</tr>
	</tbody>
</table>

app/views/users/edit.html.erb
<div class="row user-edit">
  <div class="col-xs-6 col-xs-offset-4">
    <%= form_for(@user) do |f| %>
    <%= render "devise/shared/error_messages", resource: @user %>

      <div class="field">
        <span class="need">※</span>
        <%= f.label :name, 'お名前' %><br />
        <%= f.text_field :name, autofocus: true, autocomplete: "name", class: "form-control" %>
      </div>

      <div class="field">
        <span class="need">※</span>
        <%= f.label :name_kana, 'お名前 (フリガナ)' %><br />
        <%= f.text_field :name_kana, autofocus: true, autocomplete: "name_kana", class: "form-control" %>
      </div>

      <div class="field">
        <span class="need">※</span>
        <%= f.label :nickname, 'ニックネーム' %><br />
        <%= f.text_field :nickname, autofocus: true, autocomplete: "nickname", class: "form-control" %>
      </div>

      <div class="field row">
        <%= f.label :profile_image_id, 'プロフィール画像' %><br />
        <%= f.attachment_field :profile_image, autofocus: true, autocomplete: "profile_image_id" %>
      </div>

      <div class="field">
        <%= f.label :introduction, '自己紹介 (50文字以内)' %><br />
        <%= f.text_area :introduction, autofocus: true, autocomplete: "introduction", class: "form-control" %>
      </div>

      <div class="field">
        <%= f.label :one_word, '一言メッセージ (20文字以内)' %><br />
        <%= f.text_field :one_word, autofocus: true, autocomplete: "one_word", class: "form-control" %>
      </div>

      <div class="field">
        <span class="need">※</span>
        <%= f.label :email, 'メールアドレス' %><br />
        <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
      </div>

      <div class="actions field">
        <%= f.submit "変更する", class: "btn btn-success form-control" %>
      </div>
      <div class="actions field">
        <%= link_to "パスワードの変更はこちら", user_password_edit_path(@user),class: "btn btn-primary form-control" %>
      </div>
      <div class="actions field">
        <%= link_to "退会される方はこちら", user_status_path(@user),class: "btn btn-danger form-control" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/password_edit.html.erb
<div class="row password">
	<h2 class="col-xs-6 col-xs-offset-3">パスワード再設定</h2>
  <%= form_for(@user, url:user_password_edit_path) do |f| %>
    <div class="field col-xs-6 col-xs-offset-3">
      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, autocomplete: "new-password", min: 6, class: "form-control"  %>
    </div>

    <div class="field col-xs-6 col-xs-offset-3">
      <%= f.label :password_confirmation, "パスワード(確認用)" %>
      <%= f.password_field :password_confirmation, autocomplete: "new-password",min: 6, class: "form-control" %>
    </div>

    <div class="field col-xs-6 col-xs-offset-3">
      <%= f.submit "変更する",class: "btn btn-primary form-control" %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="row user-show">
	<div class="col-xs-2">
		<!-- 会員情報 -->
		<table class="table user-info">
			<thead>
				<tr>
					<th class="row">
						<div class="col-xs-5">
							<%= link_to user_path(@user) do %>
								<%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_user.jpg", size:'70x70', class: 'user-image' %>
							<% end %>
						</div>
						<div class="col-xs-7 --right">
							<%= @user.nickname %><br>
							<% if @user.id == current_user.id %>
								<%= link_to '', edit_user_path(@user), class: 'fas fa-user-edit' %>
							<% end %>
						</div>
					</th>
				</tr>
			</thead>
			<tbody>
				<% if @user.id != current_user.id %>
					<tr>
						<td><%= render 'relationships/relation', user:@user %></td>
					</tr>
				<% end %>
				<% if @user.introduction.present? %>
					<tr>
						<td class="introduction"><%= @user.introduction %></td>
					</tr>
				<% end %>
				<% if @user.one_word.present? %>
					<tr>
						<td class="">ひとこと　<%= @user.one_word %></td>
					</tr>
				<% end %>
				<tr>
					<td><%= link_to user_path(@user) do %>
							投稿 <%= @user.posts.count %> 件
						<% end %>
					</td>
				</tr>
				<tr>
					<td><%= link_to user_follow_path(@user.id) do %>
							フォロー <%= @user.follows.count %> 人
						<% end %>
					</td>
				</tr>
				<tr>
					<td><%= link_to user_follower_path(@user.id) do %>
							フォロワー <%= @user.followers.count %> 人
						<% end %>
					</td>
				</tr>
				<% if @user.id != current_user.id %>
					<% if (current_user.following? @user) && (@user.following? current_user)  %>
						<tr>
							<td>
								<% if @isRoom == true %>
									<%= link_to 'チャットへ', room_path(@roomId) %>
								<% else %>
									<%= form_for @room do |f| %>
										<%= fields_for @entry do |e| %>
											<%= e.hidden_field :user_id, value: @user.id %>
										<% end %>
										<%= f.submit "チャットを始める", class: 'btn btn-success' %>
									<% end %>
								<% end %>
							</td>
						</tr>
					<% end %>
				<% end %>
			</tbody>
		</table>
	</div>

	<div class="col-xs-8">
		<!-- スライドショー -->
		<div id="slide-box">
		    <div id="slide">
		    	<% if Favorite.exists?(user_id: @user.id) %>
					<% @slide.each do |post| %>
						<% if post.favorited_by?(@user) %>
							<% post.post_images.each do |post_image| %>
								<%= attachment_image_tag post_image, :image %>
							<% end %>
						<% end %>
					<% end %>
				<% else %>
					<%= image_tag 'no_favorite.png' %>
				<% end %>
		    </div>
		</div>

		<!-- 会員投稿一覧 -->
		<%= render 'posts/posts', posts:@user_posts %>
	</div>
</div>

app/views/users/status.html.erb
<div class="row customer-status">
  <div class="text-center">
    <div>
      <p><strong>本当に退会しますか？</strong></p>
      <p>
        退会すると、会員登録情報や<br>
        これまでの投稿が閲覧できなくなります。<br>
        退会する場合は、『退会する』をクリックしてください。
      </p>
    </div>
    <div class="customer-status-btn">
      <% if user_signed_in? %>
        <%= link_to "退会する", user_status_path(current_user), method: :patch, "data-confirm" => "本当に退会しますか？", class: "btn btn-danger" %>
        <%= link_to "退会しない", edit_user_path(current_user), class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>